[versions]
ktor = "2.3.5"
kotlin = "1.9.20"

[libraries]
ktor-server-auth = { module = "io.ktor:ktor-server-auth-jvm" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm" }
ktor-server-jwt = { module = "io.ktor:ktor-server-auth-jwt-jvm" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm"}
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation" }